
title: 
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# 插件
plugins:
  - jekyll-feed # 订阅(未使用)
  - jekyll-avatar # GitHub头像
  - jekyll-sitemap # 搜索站点地图
  - jekyll-titles-from-headings # 标题未指定时使用markdown标题

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      pageType: blog
  - scope:
      path: ""
      type: "default"
    
# 压缩文件
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
sass:
  style: compressed